### import a numpy library to use array

In [55]:
import numpy as np

### Crate a list of python in order to convert in array

In [56]:
list = [1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### convert a python list in a array object of numpy

In [57]:
arr = np.array(list)

In [58]:
# array with 1 dimension
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# checking type pf arr variable
type(arr)

numpy.ndarray

In [60]:
# matriz is an array with 2 dimension
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
type(matrix)

list

In [62]:
matrix = np.array(matrix)

# index

### operate with 1 dimension


In [63]:
arr[1]

2

In [64]:
arr[1]+arr[0]

3

##### operate with 2 dimension


In [65]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
matriz[0]

array([1, 2, 3])

In [67]:
matriz[0,1]

2

# Slice
### to obtain a group of value of array

In [68]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[0:3]
arr[:5]
arr[0:]
arr[:]
arr[::2]




array([1, 3, 5, 7, 9])

In [72]:
## Slice in matrix

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
matrix[1:, 0:1]

array([[4],
       [7]])