### import a numpy library to use array

In [1]:
import numpy as np

### Crate a list of python in order to convert in array

In [2]:
list = [1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### convert a python list in a array object of numpy

In [3]:
arr = np.array(list)

In [4]:
# array with 1 dimension
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# checking type pf arr variable
type(arr)

numpy.ndarray

In [6]:
# matriz is an array with 2 dimension
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
type(matrix)

list

In [8]:
matrix = np.array(matrix)

# index

### operate with 1 dimension


In [9]:
arr[1]

np.int64(2)

In [10]:
arr[1]+arr[0]

np.int64(3)

##### operate with 2 dimension


In [11]:
matriz

NameError: name 'matriz' is not defined

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[0,1]

2

# Slice
### to obtain a group of value of array

In [ ]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:3]
arr[:5]
arr[0:]
arr[:]
arr[::2]




array([1, 3, 5, 7, 9])

In [ ]:
## Slice in matrix

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[1:, 0:1]

array([[4],
       [7]])