In [1]:
import numpy as np

In [2]:
arr =  np.array([0,1,2,3,4])
arr.dtype

dtype('int64')

### change data type re define variable

In [3]:
arr =  np.array([0,1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [4]:
arr

array([0., 1., 2., 3., 4.])

### change data type with a astype method

In [5]:
arr = arr.astype(np.int64)
arr
arr.dtype

dtype('int64')

In [6]:
arr = arr.astype(np.float64)
arr
arr.dtype

dtype('float64')

In [7]:
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [8]:
arr =  np.array([0,1,2,3,4], dtype="float64")
arr = arr.astype(np.string_)
arr

AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.

In [ ]:
arr =  np.array(["0","1","2","3","4"])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

## a unique type of data should be in a array