In [38]:
import numpy as np

In [39]:
arr =  np.array([0,1,2,3,4])
arr.dtype

dtype('int64')

### change data type re define variable

In [40]:
arr =  np.array([0,1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [41]:
arr

array([0., 1., 2., 3., 4.])

### change data type with a astype method

In [42]:
arr = arr.astype(np.int64)
arr
arr.dtype

dtype('int64')

In [43]:
arr = arr.astype(np.float64)
arr
arr.dtype

dtype('float64')

In [44]:
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [45]:
arr =  np.array([0,1,2,3,4], dtype="float64")
arr = arr.astype(np.string_)
arr

array([b'0.0', b'1.0', b'2.0', b'3.0', b'4.0'], dtype='|S32')

In [46]:
arr =  np.array(["0","1","2","3","4"])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

## a unique type of data should be in a array