In [1]:
import numpy as np

In [3]:
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
zero_arr = np.zeros((10,10))
print(zero_arr)
zero_arr.ndim

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


2

In [16]:
one_arr = np.ones((10,10))
print(one_arr)
one_arr.ndim

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2

In [22]:
# distribution from 0 to 10 of 100 values
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(4)

array([0.78122397, 0.58263345, 0.43051742, 0.72361206])

In [26]:
np.random.rand(4,4)

array([[0.77956654, 0.74556855, 0.93690611, 0.25816649],
       [0.0785283 , 0.65002912, 0.97839009, 0.28780873],
       [0.49926203, 0.85410736, 0.24803562, 0.61478978],
       [0.74333161, 0.65030316, 0.69965737, 0.87340811]])

In [30]:
np.random.randint(1,15)


7

In [31]:
np.random.randint(1,15, (10,10))


array([[ 7,  5, 13,  2,  7,  5,  9, 11,  7, 10],
       [12, 13, 12, 14, 12,  8,  9,  8,  4,  7],
       [ 5, 14,  8, 14,  3,  7,  1,  1, 11,  4],
       [13, 11,  5,  1,  7, 12, 10,  2, 13,  5],
       [ 9,  3,  6, 11,  5,  1,  5,  3, 14,  8],
       [ 4, 14, 11, 14,  7,  1,  6,  8,  9,  5],
       [ 8,  2, 14,  6, 10, 12,  9, 13, 14, 13],
       [10, 10, 13,  8,  3, 12,  3, 14, 10, 12],
       [ 6,  4, 14, 10,  5, 13,  5, 10,  5, 13],
       [11,  7,  9,  8, 14, 11,  2, 13,  3,  6]])