In [1]:
import numpy as np

In [6]:
arr = np.random.randint(1,10,(3,2))
arr

array([[5, 7],
       [1, 2],
       [2, 9]])

In [5]:
arr.shape

(3, 2)

In [7]:
arr.reshape(1,6)

array([[5, 7, 1, 2, 2, 9]])

In [10]:
# another way to apply a reshape 
np.reshape(arr,(1,6))

array([[5, 7, 1, 2, 2, 9]])

In [11]:
np.reshape(arr,(2,3))

array([[5, 7, 1],
       [2, 2, 9]])

In [12]:
np.reshape(arr,(2,3), 'C')

array([[5, 7, 1],
       [2, 2, 9]])

In [13]:
np.reshape(arr,(2,3), 'F')

array([[5, 2, 2],
       [1, 7, 9]])

In [14]:
np.reshape(arr,(2,3), 'A')

array([[5, 7, 1],
       [2, 2, 9]])