In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[4, 3],
       [3, 4],
       [7, 8]])

In [3]:
arr.shape

(3, 2)

In [4]:
arr.reshape(1,6)

array([[4, 3, 3, 4, 7, 8]])

In [5]:
# another way to apply a reshape 
np.reshape(arr,(1,6))

array([[4, 3, 3, 4, 7, 8]])

In [6]:
np.reshape(arr,(2,3))

array([[4, 3, 3],
       [4, 7, 8]])

In [7]:
np.reshape(arr,(2,3), 'C')

array([[4, 3, 3],
       [4, 7, 8]])

In [8]:
np.reshape(arr,(2,3), 'F')

array([[4, 7, 4],
       [3, 3, 8]])

In [9]:
np.reshape(arr,(2,3), 'A')

array([[4, 3, 3],
       [4, 7, 8]])