In [113]:
import numpy as np

In [114]:
arr = np.random.randint(1,20,10)


In [115]:
matrix = arr.reshape(2,5)

In [116]:
arr

array([12,  7,  6,  9, 17, 18, 11,  8,  5, 15])

In [117]:
arr.max()

18

In [118]:
matrix

array([[12,  7,  6,  9, 17],
       [18, 11,  8,  5, 15]])

In [119]:
# max in all matrix
matrix.max()

18

In [120]:
# max by rows
matrix.max(1)

array([17, 18])

In [121]:
# max by columns
matrix.max(0)

array([18, 11,  8,  9, 17])

In [122]:
# find index of max value in matrix
arr.argmax()

5

In [123]:
arr

array([12,  7,  6,  9, 17, 18, 11,  8,  5, 15])

In [124]:
arr[9]

15

In [125]:
matrix.argmax()

5

In [126]:
matrix

array([[12,  7,  6,  9, 17],
       [18, 11,  8,  5, 15]])

In [127]:
matrix.argmax(0)

array([1, 1, 1, 0, 0])

In [128]:
matrix.argmax(1)

array([4, 0])

In [129]:
arr.min()

5

In [130]:
# min by columns
matrix.min(0)

array([12,  7,  6,  5, 15])

In [131]:
# min by rows
matrix.min(1)

array([6, 5])

# distance between two values

In [132]:
arr

array([12,  7,  6,  9, 17, 18, 11,  8,  5, 15])

In [133]:
arr.ptp()

13

In [134]:
np.percentile(arr,50)

10.0

In [135]:
np.percentile(arr,0)

5.0

In [136]:
np.percentile(arr,100)

18.0

In [137]:
np.sort(arr)

array([ 5,  6,  7,  8,  9, 11, 12, 15, 17, 18])

In [138]:
arr.sort()
arr

array([ 5,  6,  7,  8,  9, 11, 12, 15, 17, 18])

In [139]:
np.median(arr)

10.0

In [140]:
matrix

array([[ 5,  6,  7,  8,  9],
       [11, 12, 15, 17, 18]])

In [141]:

# median by rows
# median is the 50 percentil it is not the average
np.median(matrix,1)

array([ 7., 15.])

In [142]:
# median by columns
np.median(matrix,0)

array([ 8. ,  9. , 11. , 12.5, 13.5])

In [143]:
arr

array([ 5,  6,  7,  8,  9, 11, 12, 15, 17, 18])

In [144]:
# standard desviation
np.std(arr)

4.3772137256478585

In [145]:
# variance

np.var(arr)

19.160000000000004

In [146]:
np.std(arr) ** 2

19.160000000000007

In [147]:
# mean is the average is not meadin = 50 percentile
np.mean(arr)

10.8

# Join arrays

In [148]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [149]:
a

array([[1, 2],
       [3, 4]])

In [150]:
b

array([5, 6])

In [151]:
print(a.ndim, b.ndim)

2 1


In [152]:
# overwrite b
b = np.expand_dims(b,axis=0)
np.ndim(b)

2

In [153]:
# concatenate by columns
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
# to concate by rows
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [155]:
# to solve with reshape

b = np.reshape(b,(2,1))
b

array([[5],
       [6]])

In [156]:
# without error
np.concatenate((a,b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [159]:
b = np.reshape(b,(1,2))
b


array([[5, 6]])

In [160]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])