In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)


In [5]:
matrix = arr.reshape(2,5)

In [6]:
arr

array([ 5, 14,  5,  8,  2,  9,  9, 16, 10, 17])

In [8]:
arr.max()

17

In [7]:
matrix

array([[ 5, 14,  5,  8,  2],
       [ 9,  9, 16, 10, 17]])

In [11]:
# max in all matrix
matrix.max()

17

In [13]:
# max by rows
matrix.max(1)

array([14, 17])

In [14]:
# max by columns
matrix.max(0)

array([ 9, 14, 16, 10, 17])

In [15]:
# find index of max value in matrix
arr.argmax()

9

In [18]:
arr

array([ 5, 14,  5,  8,  2,  9,  9, 16, 10, 17])

In [17]:
arr[9]

17

In [19]:
matrix.argmax()

9

In [21]:
matrix

array([[ 5, 14,  5,  8,  2],
       [ 9,  9, 16, 10, 17]])

In [20]:
matrix.argmax(0)

array([1, 0, 1, 1, 1])

In [22]:
matrix.argmax(1)

array([1, 4])

In [23]:
arr.min()

2

In [26]:
# min by columns
matrix.min(0)

array([5, 9, 5, 8, 2])

In [27]:
# min by rows
matrix.min(1)

array([2, 9])