In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)


In [3]:
matrix = arr.reshape(2,5)

In [4]:
arr

array([16,  7, 15, 15, 15, 14, 13,  5,  4, 10])

In [5]:
arr.max()

np.int64(16)

In [6]:
matrix

array([[16,  7, 15, 15, 15],
       [14, 13,  5,  4, 10]])

In [7]:
# max in all matrix
matrix.max()

np.int64(16)

In [8]:
# max by rows
matrix.max(1)

array([16, 14])

In [9]:
# max by columns
matrix.max(0)

array([16, 13, 15, 15, 15])

In [10]:
# find index of max value in matrix
arr.argmax()

np.int64(0)

In [11]:
arr

array([16,  7, 15, 15, 15, 14, 13,  5,  4, 10])

In [12]:
arr[9]

np.int64(10)

In [13]:
matrix.argmax()

np.int64(0)

In [14]:
matrix

array([[16,  7, 15, 15, 15],
       [14, 13,  5,  4, 10]])

In [15]:
matrix.argmax(0)

array([0, 1, 0, 0, 0])

In [16]:
matrix.argmax(1)

array([0, 0])

In [17]:
arr.min()

np.int64(4)

In [18]:
# min by columns
matrix.min(0)

array([14,  7,  5,  4, 10])

In [19]:
# min by rows
matrix.min(1)

array([7, 4])

# distance between two values

In [20]:
arr

array([16,  7, 15, 15, 15, 14, 13,  5,  4, 10])

In [21]:
arr.ptp()

AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.

In [ ]:
np.percentile(arr,50)

10.0

In [ ]:
np.percentile(arr,0)

5.0

In [ ]:
np.percentile(arr,100)

18.0

In [ ]:
np.sort(arr)

array([ 5,  6,  7,  8,  9, 11, 12, 15, 17, 18])

In [ ]:
arr.sort()
arr

array([ 5,  6,  7,  8,  9, 11, 12, 15, 17, 18])

In [ ]:
np.median(arr)

10.0

In [ ]:
matrix

array([[ 5,  6,  7,  8,  9],
       [11, 12, 15, 17, 18]])

In [ ]:

# median by rows
# median is the 50 percentil it is not the average
np.median(matrix,1)

array([ 7., 15.])

In [ ]:
# median by columns
np.median(matrix,0)

array([ 8. ,  9. , 11. , 12.5, 13.5])

In [ ]:
arr

array([ 5,  6,  7,  8,  9, 11, 12, 15, 17, 18])

In [ ]:
# standard desviation
np.std(arr)

4.3772137256478585

In [ ]:
# variance

np.var(arr)

19.160000000000004

In [ ]:
np.std(arr) ** 2

19.160000000000007

In [ ]:
# mean is the average is not meadin = 50 percentile
np.mean(arr)

10.8

# Join arrays

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([5, 6])

In [ ]:
print(a.ndim, b.ndim)

2 1


In [ ]:
# overwrite b
b = np.expand_dims(b,axis=0)
np.ndim(b)

2

In [ ]:
# concatenate by columns
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# to concate by rows
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
# to solve with reshape

b = np.reshape(b,(2,1))
b

array([[5],
       [6]])

In [ ]:
# without error
np.concatenate((a,b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
b = np.reshape(b,(1,2))
b


array([[5, 6]])

In [ ]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])