In [1]:
import numpy as np

In [10]:
# linspace to create an array from first value to second value and 3rd value as a total values
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [11]:
arr >  5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
cond_index = arr > 5
cond_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [13]:
# to filter with an external variable. Array display True boolean values
arr[cond_index]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [14]:
# same way
arr[arr>5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [21]:
# and condition
arr[(arr>5) & (arr<8)]

array([6, 7], dtype=int8)

In [22]:
# change values acooridng to a conditino
arr[(arr>5)] = 0

In [23]:
arr

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0], dtype=int8)

In [24]:
arr[(arr==0)]

array([0, 0, 0, 0, 0], dtype=int8)