In [1]:
import numpy as np

In [2]:
list = [1,2]
list

[1, 2]

In [4]:
# multiply two time the list, however python duplicate the list
list * 2

[1, 2, 1, 2]

In [10]:
# Solve with numpy
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr_2 = np.copy(arr)

In [12]:
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr_2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr_sum = arr_2 +1
arr_sum

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_mul = arr_2 * 2
arr_mul

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
arr_div = 1 / arr_2
arr_div

/var/folders/5f/8wn5rtw909qbjlpmf_jgrh4h0000gn/T/ipykernel_30695/3690013167.py:1: RuntimeWarning: divide by zero encountered in divide
  arr_div = 1 / arr_2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [21]:
arr + arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
arr * arr_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
matrix = np.reshape(arr, (2,5))
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
matrix_2 = matrix.T
matrix_2

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [26]:
# producto punto de matrices, la primera por la segunda traspuesta
matrix @ matrix_2

array([[ 30,  80],
       [ 80, 255]])

In [28]:
np.matmul(matrix, matrix_2)

array([[ 30,  80],
       [ 80, 255]])